name: iOS Build

on:
  workflow_dispatch: # запуск вручну
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13  # або macos-13, залежно від того, що доступно

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Install CocoaPods (if needed)
        run: |
          if [ -f "LaserDetector-Stylish-Advanced/Podfile" ]; then
            sudo gem install cocoapods
            cd LaserDetector-Stylish-Advanced
            pod install
          fi

      - name: Build archive
        run: |
          cd LaserDetector-Stylish-Advanced
          if [ -d "LaserDetector.xcworkspace" ]; then
            xcodebuild \
              -workspace LaserDetector.xcworkspace \
              -scheme LaserDetector \
              -sdk iphoneos \
              -configuration Release \
              archive \
              -archivePath $GITHUB_WORKSPACE/build/LaserDetector.xcarchive
          else
            xcodebuild \
              -project LaserDetector.xcodeproj \
              -scheme LaserDetector \
              -sdk iphoneos \
              -configuration Release \
              archive \
              -archivePath $GITHUB_WORKSPACE/build/LaserDetector.xcarchive
          fi

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/LaserDetector.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $GITHUB_WORKSPACE/build/ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaserDetector-ipa
          path: build/ipa/*.ipa
