name: iOS Build (IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch: # можна запускати вручну

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.12.0
        
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install CocoaPods (if Podfile exists)
        run: |
          if [ -f "LaserDetector/Podfile" ]; then
            sudo gem install cocoapods
            cd LaserDetector
            pod install
          fi

      - name: Build archive
        run: |
          cd LaserDetector
          if [ -d "LaserDetector.xcworkspace" ]; then
            xcodebuild \
              -workspace LaserDetector.xcworkspace \
              -scheme LaserDetectorApp \
              -sdk iphoneos \
              -configuration Release \
              archive \
              -archivePath $GITHUB_WORKSPACE/build/LaserDetector.xcarchive \
              CODE_SIGNING_ALLOWED=NO
          else
            xcodebuild \
              -project LaserDetector.xcodeproj \
              -scheme LaserDetectorApp \
              -sdk iphoneos \
              -configuration Release \
              archive \
              -archivePath $GITHUB_WORKSPACE/build/LaserDetector.xcarchive \
              CODE_SIGNING_ALLOWED=NO
          fi

      - name: Export IPA
        run: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF

          xcodebuild \
            -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/LaserDetector.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $GITHUB_WORKSPACE/build/ipa \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaserDetector-ipa
          path: build/ipa/*.ipa
